version: '3'
services:
  aeon-pool:
    build: .
    container_name: aeon-pool
    environment:
      - POOL_WALLET_ADDRESS=14JeLuxP47oMSyF5pV3gHshoRRVY7mXpr3YbpvyEvhRPiTtjjjngYx6XmmkuzQJL9qadP8gedtru4BNBZESu8oESHGVgCMk
      - POOL_API_PASSWORD=A1password
      - POOL_HOST=mail.ducx.io
      - POOL_API=https:\/\/mail.ducx.io:8119
      - MAIL_ADDRESS=lecrab@gmail.com

networks:
  default:
    external:
      name: "crypto-pool-net"
