version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: nginx
    environment:
      NGINX_HOST: mail.ducx.io
    networks:
      - crypto-pool-net

  aeon-redis:
    build:
      context: redis
    container_name: aeon-redis
    volumes:
      - redis-data-aeon:/data
    networks:
      - crypto-pool-net

  ducx-wallet:
    build:
      cryptonote-docker
    container_name: ducx-wallet
    environment:
        - WALLET_NAME=pool.bin
        - WALLET_PASSWORD=""
        - WALLET_PORT=59995
        - WALLETD_PORT=59996
    volumes:
      - wallet-data-ducx:/wallet
    networks:
      - crypto-pool-net
    command:
      build/release/src/ducxd
      --rpc-bind-ip 0.0.0.0

  aeon-pool:
    build:
      context: pool
    container_name: aeon-pool
    depends_on:
      - aeon-redis
    environment:
      - POOL_WALLET_ADDRESS=ducx-wallet
      - POOL_API_PASSWORD=pass
      - POOL_HOST=mail.ducx.io
      - POOL_API=https:\/\/mail.ducx.io:8119
      - MAIL_ADDRESS=lecrab@gmail.com
    networks:
      - crypto-pool-net

  haproxy:
    build:
      context: haproxy
    container_name: haproxy
    depends_on:
      - aeon-pool
      - ducx-wallet
      - nginx
    ports:
      - "80:80"
      - "443:443"
      - "3333:3333"
      - "3334:3334"
      - "3335:3335"
      - "3336:3336"
      - "8117:8117"
      - "8119:8119"
      - "9999:9999"
    volumes:
      - haproxy-data:/etc/letsencrypt
    environment:
      - HAPROXY_STATS_PASSWORD=pass
      - AEON_WEB_DOMAIN=mail.ducx.io
      - AEON_PORT_LOW=3333
      - AEON_PORT_MED=3334
      - AEON_PORT_HIG=3335
      - AEON_PORT_EXT=3336
      - AEON_API_PORT=8119
    networks:
      - crypto-pool-net


volumes:
  wallet-data-ducx:
  redis-data-aeon:
  pool-data-aeon:
  haproxy-data:

networks:
  crypto-pool-net:
    external: true
